services:
  - type: web
    name: bowerycreative-socialmanager
    runtime: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: FB_REDIRECT_URI
        sync: false
      - key: EMAIL_API_KEY
        sync: false
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true